#!/bin/sh
######################################################################
#   _  __ _         _                                                #
#  (_)/ _| |   __ _| |__     This software is distributed by iflab.  #
#  | |  _| |__/ _` | '_ \      For more information,please email     #
#  |_|_| |____\__,_|_.__/             project@iflab.org.             #
#                                                                    #
######################################################################

[ -f /etc/motd.iflab ] && cat /etc/motd.iflab || true